version: '3'
services:
  fluentd:
    image: ${USERNAME}/fluentd
    #image: fluentd:v1.16.2-1.1
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    depends_on:
      - "elasticsearch"

  zipkin:
    image: openzipkin/zipkin:2.21.0
    ports:
      - "9411:9411"
    networks:
      - back_net
      - front_net

  elasticsearch:
    image: elasticsearch:7.4.0
    #image: docker.elastic.co/elasticsearch/elasticsearch:7.13.1
    environment:
      - ELASTIC_CLUSTER=false
      - CLUSTER_NODE_MASTER=true
      - CLUSTER_MASTER_NODE_NAME=es01
      - discovery.type=single-node
    expose:
      - 9200
    ports:
      - "9200:9200"

  kibana:
    image: kibana:7.4.0
    #image: docker.elastic.co/kibana/kibana:7.13.1
    ports:
      - "5601:5601"
    depends_on:
      - "elasticsearch"
