version: '3.3'
services:
  post_db:
    image: mongo:latest
    volumes:
      - reddit_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
  ui:
    build: ../src/ui
    image: ${UUSERNAME}/ui:${UI_IMAGE_TAG}
    ports:
      - ${PUBLISH_PORTS}:${PUBLISH_PORTS}/tcp
    networks:
      - front_net
    depends_on:
      - comment
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui
  post:
    build: ../src/post-py
    image: ${UUSERNAME}/post:${POST_IMAGE_TAG}
    depends_on:
      - post_db
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    networks:
      - back_net
      - front_net
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post
        fluentd-async: 'true'
  comment:
    build: ../src/comment
    image: ${UUSERNAME}/comment:${COMMENT_IMAGE_TAG}
    depends_on:
      - post
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    networks:
      - back_net
      - front_net

  prometheus:
    image: ${UUSERNAME}/prometheus
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command: # Передаем доп параметры в командной строке
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d' # Задаем время хранения метрик в 1 день
    networks:
      front_net:
        aliases:
          - post_db
          - comment_db

  node-exporter:
    image: prom/node-exporter:v0.15.2
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      front_net:

volumes:
  reddit_db:
  prometheus_data:
  blackbox_exporter:

networks:
  back_net:
  front_net:
