version: '3.3'
services:
  post_db:
    image: mongo:latest
    volumes:
      - reddit_db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
  ui:
    build: ../src/ui
    image: ${UUSERNAME}/ui:${UI_IMAGE_TAG}
    ports:
      - ${PUBLISH_PORTS}:${PUBLISH_PORTS}/tcp
    networks:
      - front_net
    depends_on:
      - comment
  post:
    build: ../src/post-py
    image: ${UUSERNAME}/post:${POST_IMAGE_TAG}
    depends_on:
      - post_db
    networks:
      - back_net
      - front_net
  comment:
    build: ../src/comment
    image: ${UUSERNAME}/comment:${COMMENT_IMAGE_TAG}
    depends_on:
      - post
    networks:
      - back_net
      - front_net

  prometheus:
    image: ${UUSERNAME}/prometheus
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command: # Передаем доп параметры в командной строке
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d' # Задаем время хранения метрик в 1 день
    networks:
      front_net:
        aliases:
          - post_db
          - comment_db

  node-exporter:
    image: prom/node-exporter:v0.15.2
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      front_net:

  blackbox:
    image: ${UUSERNAME}/blackbox_exporter:${BLACKBOX_IMAGE_TAG}
    ports:
    - 9115:9115
    command: # Передаем доп параметры в командной строке
      - '--config.file=/config/blackbox.yml'
    networks:
      front_net:

  mongodb-exporter:
    image: percona/mongodb_exporter:0.20
    ports:
      - 27117:27017
      - 9216:9216
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password
    command:  '--mongodb.uri=mongodb://127.0.0.1:27017'
    networks:
      front_net:

volumes:
  reddit_db:
  prometheus_data:
  blackbox_exporter:

networks:
  back_net:
  front_net:
