version: '3.3'
services:
  post_db:
    image: mongo:latest
    volumes:
      - reddit_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
  ui:
    build: ./ui
    image: ${UUSERNAME}/ui:${UI_IMAGE_TAG}
    ports:
      - ${PUBLISH_PORTS}:${PUBLISH_PORTS}/tcp
    networks:
      - front_net
    depends_on:
      - comment
  post:
    build: ./post-py
    image: ${UUSERNAME}/post:${POST_IMAGE_TAG}
    depends_on:
      - post_db
    networks:
      - back_net
      - front_net
  comment:
    build: ./comment
    image: ${UUSERNAME}/comment:${COMMENT_IMAGE_TAG}
    depends_on:
      - post
    networks:
      - back_net
      - front_net

volumes:
  reddit_db:

networks:
  back_net:
  front_net:
